gjsify/ts-for-gir

- examples/browser/main.ts
- examples/editor/main.ts
- examples/editor/webpack.config.js
- main.ts
- out/AppIndicator3.d.ts
- out/Atk.d.ts
- out/GLib.d.ts
- out/GModule.d.ts
- out/GObject.d.ts
- out/Gdk.d.ts
- out/GdkPixbuf.d.ts
- out/Gio.d.ts
- out/GtkSource.d.ts
- out/Notify.d.ts
- out/Pango.d.ts
- out/Soup.d.ts
- out/WebKit.d.ts
- out/cast.ts
- package-lock.json
- package.json
- tsconfig.json
This changes API for runtime-checking casts to allow for tree-shaking it.
|           | old  | new  |
|-----------|------|------|
| no minify | 75.9kiB | 148kiB  |
| minify    | 66.4kiB | 1.51kiB |
In this PR I also updated generated definitions in out directory and added package-lock.json generated by npm 5.
I also updated examples to match newly generated bindings.
> Tree shaking

- main.ts
Signal connect methods return a number which can be used as a reference for disconnect methods, but ts-for-gjs was generating signatures that returned void.
> connect methods return a number

- main.ts
Consulting the [wkik](https://gitlab.gnome.org/GNOME/gjs/wikis/Mapping#gtype-objects) I found that in gjs GType is not represented as a number, but an object with a `name` field; its numeric value is not made public. Classes should have a `static $gtype: Object.GType` member so one can read their type.
> Fix GType and add $gtype properties

- main.ts
[According to the gks wiki](https://gitlab.gnome.org/GNOME/gjs/wikis/Mapping#signals) GObjects have methods for signals, but these were missing from ts-for-gjs' output, so I've added them.
Sorry this can't be merged cleanly. I think it's because I originally added this to the wrong branch, and tried to patch it into a clean branch from upstream afterwards, but something seems to have gone wrong. If it's a problem I'll try doing it over again.
> Signal methods

- main.ts
For some reason these got missed from my earlier PR(s). These symbols are currently only used by registerClass internally, but they are exported by gjs' Object module and could be useful for a proposed decorator-based replacement for registerClass.
> Export symbols used by registerClass

- templates/node-gtk/index.d.ts
Without <%_, the preceeding space won't be removed and will be included
in front of any following line. This has significance when outputing
`// <reference` line, as TS (at least in VSCode) won't read the line if
it's indented at all.
> template: uses <%_ to fix indent of node-gtk's index.d.ts

- examples/Gjs/editor/main.ts
- templates/Gjs/cast.ts
The first improvement is typing `inheritanceTable` as indexable, which
enables us not to cast it to `any` needlessly, improving type safely.
The second improvement is making `StaticNamed` interface a generic and
adding construct signature. This way, TypeScript will be able to infer
the type parameter of `giCast`, which allow users to write:
```js
const buf = giCast(srcView.buffer, GtkSource.Buffer)
```
without writing the type twice.
> template: improve typing for cast.ts

- package.json
When oclif detects src/-lib/ split, it'll try to use .ts files in src/
directly. If ts-node isn't installed, it'll fail and won't re-try the
file in lib/, thus failing the run entirely.
Add ts-node as a devDep fixes the issue and allow the command to run
directly in-tree.
> package.json: add ts-node as devDep to fix running in-tree

- src/config.ts
This enables Darwin systems to work OOB, without needing to specify additional directories on the configuration.
> Use /usr/local/share when on Darwin systems

- README.md
Seems there was a typo in the README.md and the quote was forgotten
> Missing quote in generate example

- src/index.ts
... to avoid the type-unknown error during installation.
> Add the type for ex

- src/gir-module.ts
- src/type-definition-generator.ts
First, fix a reversal of logic: output a "readonly" property when the
property _is_ readonly, and mark a property as readonly when a property
_is not_ writable.
Then, handle the construct-only property correctly: when a property is
construct-only, the property shouldn't vanish when not in construct
prop. Instead, the property should appear as a readonly.
The first case should fix GstObject's 'name' property appears as
'readonly' in subclasses (it isn't), while the second case should fix
GstPad's 'direction' property missing.
-----------------------------------------------------
This is an example of changes which my commit intended to make (only the first 2 hunks):
```patch
diff --git a/@types/node-gtk/Gst-1.0.d.ts b/@types/node-gtk/Gst-1.0.d.ts
index 0ac0d9d..e03730d 100644
--- …
```
> Fix logic around property's readonly & construct-only

- examples/node-gtk/browser/package.json
- examples/node-gtk/builder-auto-connect-signals/package.json
- examples/node-gtk/builder/package.json
- examples/node-gtk/cli/package.json
- examples/node-gtk/editor/package.json
- examples/node-gtk/hello-gtk/package.json
- package-lock.json
- package.json
Hello,
This PR address the issue #64 and also updates some dependencies  
Changes:
- Remove @types/change-case dep, not necessary anymore
- Update async and ejs due to vulnerabilities (npm audit fix)
- Update TypeScript minor version
> Change engine version to >16

- templates/Gjs/index.d.ts
Hello,
This PR intends to revert a [mistake I made](https://github.com/sammydre/ts-for-gir/pull/67/files#diff-a6b8083e7461cce7cc3413ca471e7d9d0a8bdf18911a2a6e777c0fcbc689f12bL260-L269) in #67, which was the removal of the global definition for `imports.verision`
> Revert removal of imports.versions

- templates/Gjs/module.js
Hello,
Currently, when using the type definitions generated by this tool with the Typescript compiler it complains about not being able to find the modules imported by the generated .js files
This is an expected behaviour considering TS doesn't understand `gi://` imports, and that doesn't really impact its type checking due to it resolving everything through the `d.ts` files.
So, this PR adds to the `module.js` template, used to generate the `.js` files, a `@ts-expect-error` annotation on top of the `gi://` imports to avoid TS compiling errors
> Tell tsc to expect error on gi ESM imports

- templates/Gjs/index.d.ts
Hello,
This PR is a simple improvement to the type definition of log/logError's arguments.
According to gjs implementation, the `log` function takes a required `any` typed argument, as it internally convert it to string, by calling the `ToString` method:
https://gitlab.gnome.org/GNOME/gjs/-/blob/1.72.0/modules/print.cpp#L29-32
https://gitlab.gnome.org/GNOME/gjs/-/blob/1.72.0/modules/print.cpp#L37
Also, `logError` requires a more restrictive type for the `exception` argument, as it throws an Exception if it is any primitive type (such as: string, number, bigint, boolean, undefined, symbol, and null) and only accepts objects. As for the `message` argument, it accepts `any` because it converts it to string just like `log` above:
https://gitlab.gnome.org/GNOME/gjs/-/blob/1.72.0/modules/print.c …
> Improve log/logError argument types

- packages/cli/src/type-definition-generator.ts
Hello,
In GJS's source code, all GIRepositoryNamespace (Object representing imported GIR libraries) expose two underscored properties containing the lib name and version:
https://gitlab.gnome.org/GNOME/gjs/-/blob/master/gi/ns.cpp#L186-190
This PR exposes those properties in the Typescript namespace definition for each processed lib.
> Expose GIRepositoryNamespace underscore properties in TS namespace

- packages/cli/src/logger.ts
Hello,
This PR fix a bug in Logger's static methods that result in the messages being printed twice:
With the following changes:
> Fix prepend logic in Logger's static methods

- README.md
- packages/cli/package.json
- packages/cli/src/config.ts
- packages/cli/src/messages.ts
- packages/cli/src/types/generate-config.ts
- packages/cli/src/types/user-config.ts
- packages/cli/src/utils.ts
- packages/cli/templates/Gjs/index.d.ts
Hello,
This PR presents a solution for #72. It adds a notice to the README informing users that it is recommended to edit their `tsconfig.json` file for GJS projects. Besides, logic was built to check, during runtime, if the project has the `DOM` lib in its `tsconfig.json` and if that is the case ask the user if he wants to skip generating any conflicting type.
Also, included in this PR are the definitions for the Text(D)Encoder interfaces added in GJS 1.69.2:
https://gitlab.gnome.org/GNOME/gjs/-/blob/572f8e8c/NEWS#L384-393
https://gitlab.gnome.org/GNOME/gjs/-/blob/master/doc/Encoding.md
https://gitlab.gnome.org/GNOME/gjs/-/blob/master/modules/esm/_encoding/encoding.js
> Solution for #72 + Add type definitions for Text(D)Encoder

- packages/cli/src/conflict-resolver.ts
Hello,
This is a better solution for #87.
It changes the conflict resolution logic for classes signals. Now it accepts methods as overloads for parent signals, and pull incompatible parent methods as overloads for signals. As far as I could test, this allows for classes that implement `methods` with incompatible signature to `propertySignalMethods` be properly typed. However, with the caveat that classes that completely override the parent implementation (such as `Gio.Cancellable.connect`) will still be typed as accepting it, even tough that is not true on runtime. I am thinking on a solution for this, but it will probably require some runtime monkey-patching, so I don't know if it will be viable. For now, I think this is a good approach to solve the original issue tough.
> Change Class Signal conflict resolution logic

- packages/cli/templates/Gjs/index.d.ts
Hello,
In GJS, the type definition for the global property `imports.signals` is missing. This PR adds it and also includes a bit of code formatting for `packages/cli/templates/Gjs/index.d.ts`
> Expose GJS global `imports.signals` type

- packages/cli/src/gir-factory.ts
- packages/cli/src/injection/classes/gjs/GLib-2.0.ts
- packages/cli/src/injection/injector.ts
- packages/cli/src/types/injection-class.ts
Hello,
In GJS, `Glib.Error` is extended to have better interoperability with JS `Error`. This PR implements these GJS specific additions as injections. Basically, `Glib.Error`'s constructor becomes a proxy for `Glib.Error.new_literal` and the `stack`, `source`, `line` and `column` properties are added to it.
Sources:
https://gjs-docs.gnome.org/glib20~2.66.1/glib.error#constructor-new_literal
https://gitlab.gnome.org/GNOME/gjs/-/blob/33d58646d43b84d4c0ffc3681b89d125d5ccdfc6/installed-tests/js/testExceptions.js#L119-123
https://gitlab.gnome.org/GNOME/gjs/-/blob/d1cf26179322b2b87fb980e3b244b5e24dba8dd6/gi/gerror.cpp#L298-305
> Enhance Glib.Error type with GJS specific additions

- packages/cli/templates/Gjs/Gjs.d.ts
Adds missing getttext functions: pgettext, dpgettext:
https://gitlab.gnome.org/GNOME/gjs/-/blob/04f7b614/modules/core/_gettext.js#L55-60
Fix getttext.domain().pgettext typing
> Add missing getttext functions: pgettext, dpgettext

- package.json
- packages/cli/package.json
- packages/cli/src/config.ts
- packages/cli/src/utils.ts
- yarn.lock
Small improvement over #86.
Replaces the runtime dependency on [typescript](https://github.com/microsoft/TypeScript) with [get-tsconfig](https://github.com/privatenumber/get-tsconfig), a compliant tsconfig.json's parser without the weight of the full typescript compiler. Besides, updates some of the dependencies and add two development dependencies used by this project's root eslint configuration that were missing: `@typescript-eslint/eslint-plugin`, `@typescript-eslint/parser`
> Replace typescript runtime dependency with get-tsconfig

- packages/cli/src/config.ts
**Problem:** running the CLI would error on NixOS as it does not have `/usr/share`:
```sh
$ yarn build; and yarn ts-for-gir generate
ERROR: No module found in /usr/share/gir-1.0!
Please make sure that you have installed the necessary gir files.
For example with "sudo apt install libgtk-3-dev" for Gtk3 on Ubuntu or "sudo dnf install gtk3-devel" on Fedora. []
```
**Solution:** use `XDG_DATA_DIRS` as commented in code.  I think this is harmless on other distros.
> fix: use correct gir paths for NixOS

- packages/lib/templates/Gjs/GObject-2.0.d.ts
Template needs to be a string for using paths to UI files instead of loading the data in separately.
> Allow Template to be a string

- packages/lib/templates/Gjs/index.d.ts
According to the [docs](https://gitlab.gnome.org/GNOME/gjs/-/blob/master/doc/Package/Specification.md), `pkg` is a global object. It should be made available for ESM projects that avoids using `imports`.
> Add pkg to global

- packages/lib/src/gir-module.ts
Node-gtk doesn't do array type override.
> fix(node-gtk): override array type only on gjs, fixes #127

- packages/generator-typescript/templates/gjs/dom.d.ts
Add to dom compatibility module because Typescript also defines this in its dom module, see https://github.com/saschanaz/types-web/blob/87cdc80239a5218065a4bde410583f0488b3073b/baselines/dom.generated.d.ts#L661
Closes https://github.com/gjsify/types/issues/4
> Add type for import.meta.url

- packages/lib/src/injections/glib.ts
> Add GLib.Error.stack property

- packages/generator-typescript/templates/gobject-2.0.d.ts
> Add Requires property to MetaInfo

- packages/lib/src/gir.ts
- packages/lib/src/gir/registry.ts
- packages/lib/src/validators/function-parameters.ts
> Mark enum parameters as nullable

- DEVELOPMENT.md
Currently the development instructions tell fedora users to run `sudo dnf update` before installing the required development packages. Considering the `sudo apt-get update` instruction in the ubuntu guide I'm assuming the intent with that instruction was to make sure people's package managers have an up to date list of available packages but `dnf update` doesn't do that, it just updates all packages on the system.
`dnf` usually takes care of refreshing its cache of package metadata on its own so the fedora instructions should be fine with just `sudo dnf install ...`
> Docs: Avoid telling developers on fedora to update their system

- packages/generator-typescript/src/module-generator.ts
TypeScript indicates module as deprecated in this context and recommends using namespace instead
> Replace keyword: module -> namespace

- packages/lib/src/injections/inject.ts
- packages/lib/src/injections/shell.ts
This PR adds support for using `Cogl.SnippetHook` in `Shell.GLSLEffect.add_glsl_snippet()` method, which is required for GNOME Shell 48+ where `Shell.SnippetHook.FRAGMENT` was removed in favor of `Cogl.SnippetHook.FRAGMENT`.
- Added support for both `Shell.SnippetHook` and `Cogl.SnippetHook` in the type definitions for Shell-14 and Shell-15
- Updated the injection logic to handle both hook types
- Added Shell 14 and 15 injections to the main inject function
Starting with GNOME 48, `Shell.SnippetHook.FRAGMENT` was removed and developers are required to use `Cogl.SnippetHook.FRAGMENT` instead. This change is documented in the [GNOME Shell 48 upgrade guide](https://gjs.guide/extensions/upgrading/gnome-shell-48.html#cogl-snippethook).
The type definitions now support both hook types to …
> feat(shell): Add Cogl.SnippetHook support for Shell.GLSLEffect.add_glsl_snippet

- examples/glib-2-variant/index.ts
This PR adds and improves examples to demonstrate the reported GLib.Variant type issues in #239. The changes focus on providing a clear test case for the reported typing problems with GLib.Variant usage in different contexts.
- Improved and restructured the `glib-2-variant` example to better demonstrate variant usage
- Added comprehensive test cases for:
- Basic variant creation and usage
- DBus signal emission with variants
- Complex variant structures
- Variant unpacking methods
- Added clear documentation and comments
- Ensured clean program termination
The example can be run with:
```bash
cd examples/glib-2-variant
yarn install
yarn start
```
- Fixes #239 (GLib.Variant type compatibility issues)
- Demonstrates the reported type errors with:
- `DBusExportedObject.emit_signal()` with …
> Add example to test GLib.Variant type issue

- packages/generator-typescript/templates/gjs/gjs.d.ts
This fixes #220 as the preferred and simpler solution instead of #226
> Global gettext methods / pkg properties are no longer undefined

- packages/generator-typescript/templates/gjs/gjs.d.ts
- Introduced `pkg.initFormat()` to initialize string formatting with printf-style specifiers.
- Updated `format` function to support various types and added detailed documentation.
- Extended the String prototype with a `format` method for easier string manipulation.
- Provided examples for usage, including formatting strings, numbers, and padding.
> Enhance string formatting capabilities in TypeScript definitions

- packages/lib/src/generics/generify.ts
This fixes #248
@ewlsh Is there any specific reason why you have marked Gtk 4 generics as required?
> Gtk 4 generics should not be required

- examples/gobject-param-spec/README.md
- examples/gobject-param-spec/main.ts
- packages/lib/src/injections/gobject.ts
The `bind_property_full` method in GObject had incorrect TypeScript type definitions where the `transform_to` and `transform_from` parameters were typed as `Closure` instead of `Closure | null`. This prevented users from passing `null` values for these parameters, even though the documentation clearly states "or %NULL to use the default".
In the GObject-2.0.gir file, the `bind_property_with_closures` method (which shadows `bind_property_full`) is missing the `nullable="1"` and `allow-none="1"` attributes for its Closure parameters, despite the documentation indicating they can be null. This is an upstream bug in the GIR file.
Interestingly, the `BindingGroup.bind_with_closures` method has the same parameters correctly marked as nullable, showing the inconsistency.
Added a specific fix in …
> fix(gobject): make bind_property_full Closure parameters nullable

- examples/adw-1-hello/package.json
- examples/gtk-3-editor/package.json
- examples/gtk-3-hello/package.json
- examples/gtk-4-template-vite/package.json
- examples/soup-3-http/package.json
- package.json
- packages/cli/package.json
- packages/generator-base/package.json
- packages/generator-html-doc/package.json
- packages/generator-typescript/package.json
- packages/lib/package.json
- yarn.lock
- Upgraded `concurrently` to version 9.2.0 in multiple package.json files.
- Updated `vite` to version 7.0.0 in example projects.
- Bumped `@types/node` to version 24.0.4 across various packages.
- Updated `prettier` to version 3.6.1 in the cli package.
- Adjusted `@parcel` dependencies to version 2.15.4 in example projects.
- Incremented `@types/lodash` to version 4.17.18 in the lib package.
> chore: Update package dependencies to latest versions
